name: Azure Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows you to manually trigger the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure
      run: |
        az login --service-principal \
          --username ${{ secrets.APPID }} \
          --password ${{ secrets.PASSWORD }} \
          --tenant ${{ secrets.TENANT_ID }}

    - name: Create Azure Function App
      run: |
        az functionapp create \
          --resource-group beyonce-api-group \
          --consumption-plan-location westus2 \
          --runtime python \
          --functions-version 4 \
          --name beyonce-api-function \
          --storage-account beyoncestorage
          --os-type Linux
